# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shync < Formula
  desc "Sync config files across devices"
  homepage "https://github.com/quangkhaidam93/shync"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.7.2/shync_0.7.2_darwin_amd64.tar.gz"
      sha256 "d6fd4ece69d610183562ee0095a9d6e85099e85e6805796a7d89ba149f35b0aa"

      define_method(:install) do
        bin.install "shync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.7.2/shync_0.7.2_darwin_arm64.tar.gz"
      sha256 "ffb93b55229f9be12afe99c61a8a9c8a93d19941e0c20ad8d678dcea37af6b50"

      define_method(:install) do
        bin.install "shync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.7.2/shync_0.7.2_linux_amd64.tar.gz"
      sha256 "e962b525172c240f23f44ed4247024ccf1070a02be7272d9e0a465e93ce61f1f"
      define_method(:install) do
        bin.install "shync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.7.2/shync_0.7.2_linux_arm64.tar.gz"
      sha256 "5c390e244dd0930ffb3f5b3f4f75ef36ba853e8ed50d43d3e28ae080ca31e1aa"
      define_method(:install) do
        bin.install "shync"
      end
    end
  end

  test do
    system "#{bin}/shync", "version"
  end
end
