# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shync < Formula
  desc "Sync config files across devices"
  homepage "https://github.com/quangkhaidam93/shync"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.7.0/shync_0.7.0_darwin_amd64.tar.gz"
      sha256 "b57e4d5dd39645c4910526ba58b8640a0ba8e9c70aafcce3a035b730893de6b3"

      define_method(:install) do
        bin.install "shync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.7.0/shync_0.7.0_darwin_arm64.tar.gz"
      sha256 "6bed86fb4921bfdf2935b68cf1b334a34bf37eceb646e5b9863e2e6f1bf57a00"

      define_method(:install) do
        bin.install "shync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.7.0/shync_0.7.0_linux_amd64.tar.gz"
      sha256 "422f3650a81db18c4df7146ae0dff74ce9ca549eb871100c384c7a8ad2dca591"
      define_method(:install) do
        bin.install "shync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.7.0/shync_0.7.0_linux_arm64.tar.gz"
      sha256 "cb74034d36fd24b004faec7a2a3b865c41da1b71943936f3ca70b0a68e341b3d"
      define_method(:install) do
        bin.install "shync"
      end
    end
  end

  test do
    system "#{bin}/shync", "version"
  end
end
