# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shync < Formula
  desc "Sync config files across devices"
  homepage "https://github.com/quangkhaidam93/shync"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.2.0/shync_0.2.0_darwin_amd64.tar.gz"
      sha256 "5059593f4c9d35ffee9f44853261502b7ad06aad4b6fa2d7c60cae1c5efb2602"

      define_method(:install) do
        bin.install "shync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.2.0/shync_0.2.0_darwin_arm64.tar.gz"
      sha256 "ce767c5374d50bdc0b3fea19f707d0cd942de0f841380aed46c1fc227f14d5f3"

      define_method(:install) do
        bin.install "shync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.2.0/shync_0.2.0_linux_amd64.tar.gz"
      sha256 "7978d8ecb2c893dd985a82d7079e355a34721e11ae9b9418f8277e5175568ca4"
      define_method(:install) do
        bin.install "shync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quangkhaidam93/shync/releases/download/v0.2.0/shync_0.2.0_linux_arm64.tar.gz"
      sha256 "98f0729e8eefa80571d3fb3cc4d70df91bd849d6be88366b4b923551d57bfbfd"
      define_method(:install) do
        bin.install "shync"
      end
    end
  end

  test do
    system "#{bin}/shync", "version"
  end
end
